# Generated by Django 3.1.3 on 2023-01-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('token_path', models.TextField()),
                ('api_key', models.CharField(max_length=225)),
                ('redirect_uri', models.CharField(max_length=225)),
                ('acc_id', models.IntegerField()),
                ('model_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('symbols', models.TextField()),
                ('scanner_symbols', models.TextField()),
                ('scanner_models', models.TextField()),
            ],
        ),
    ]
