# Generated by Django 3.1.3 on 2023-02-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='redirect_uri',
            new_name='redirect_url',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='model_name',
            new_name='trading_model',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='symbols',
            new_name='trading_symbols',
        ),
        migrations.AddField(
            model_name='user_data',
            name='run_scanner',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_data',
            name='run_trading',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
