# Generated by Django 3.1.3 on 2023-02-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20230211_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='acc_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='api_key',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='redirect_url',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='run_scanner',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='run_trading',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='scanner_models',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='scanner_symbols',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='token_path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='trading_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='trading_symbols',
            field=models.TextField(null=True),
        ),
    ]
