# Generated by Django 3.1.3 on 2023-02-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20230211_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='buy_more',
            field=models.BooleanField(null=True),
        ),
    ]
